# Generated by Django 5.2.17 on 2026-10-08 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('chess', 'Шахматы'), ('tictactoe', 'Крестики-нолики')], max_length=16, verbose_name='Игра')),
                ('result', models.CharField(choices=[('win', 'Победа'), ('loss', 'Поражение'), ('draw', 'Ничья')], max_length=8, verbose_name='Результат')),
                ('mode', models.CharField(choices=[('ai', 'Против компьютера'), ('hotseat', 'Два игрока')], default='ai', max_length=8, verbose_name='Режим')),
                ('moves', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число ходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата партии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Результат партии',
                'verbose_name_plural': 'Результаты партий',
                'ordering': ['-created_at'],
            },
        ),
    ]
