# Generated by Django 5.2.17 on 2026-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=8, null=True, verbose_name='Сложность'),
        ),
    ]
